# 异常处理

> 页面元素异常（例如按钮无法点击、元素不展示）、页面卡顿、页面白屏

**⚡题目**:

❓ 前端界面异常介绍及处理方式

## 优解 🔥

从根本上来说，异常就是一个数据结构，它存了异常发生时相关信息，譬如错误码、错误信息等。其中 message 属性是唯一一个能够保证所有浏览器都支持的属性。

- `Error`：错误的基类，其他错误都继承自该类型
- `EvalError`：Eval 函数执行异常
- `RangeError`：数组越界
- `ReferenceError`：尝试引用一个未被定义的变量时，将会抛出此异常
- `SyntaxError`：语法解析不合理
- `TypeError`：类型错误，用来表示值的类型非预期类型时发生的错误
- `URIError`：以一种错误的方式使用全局 URI 处理函数而产生的错误

最常用的异常处理方式

```js
try {
  // 可能会导致错误的代码
} catch (error) {
  // 在错误发生时怎么处理
} finally {
  // 最终都会执行代码
}
```

### 异常分析

**JS代码错误**：代码中存在执行特定类型的操作时，变量的类型并不符合要求所致等导致的，一般只需要使用 `try...catch`进行捕获。
**JS语法错误**：语法错误我们无法通过 try-catch 捕获到，不过语法错误在我们开发阶段就可以看到，应该不会顺利上到线上环境。 线上的JSON 解析出错和浏览器兼容性也会导致语法错误。

```js
try {
  JSON.parse(remoteData); // remoteData 为服务端返回的数据
} catch {
  console.error("服务端数据格式返回异常，无法解析", remoteData);
}
```

**异步错误**：`try-catch` 对语法和异步错误却无能为力，捕获不到

### 异常捕获

**window.onerror**: 同步错误可以捕获到；无法捕获静态资源异常、异步异常和 JS 代码错误。

```js
/**
 * @param {String}  message    错误信息
 * @param {String}  source     出错文件
 * @param {Number}  lineno     行号
 * @param {Number}  colno      列号
 * @param {Object}  error      Error对象（对象）
 */
window.onerror = function (message, source, lineno, colno, error) {
  console.log("捕获到异常：", { message, source, lineno, colno, error });
};
```

**静态资源加载异常**:

- `onerror`捕获: 代码的侵入性太强了，每一个静态资源标签都要加上 onerror 方法

```html
<script>
  function errorHandler(error) {
    console.log("捕获到静态资源加载异常", error);
  }
</script>
<script src="http://cdn.xxx.com/js/test.js" onerror="errorHandler(this)"></script>
<link rel="stylesheet" href="http://cdn.xxx.com/styles/test.css" onerror="errorHandler(this)">

```

- `addEventListener('error')`: 虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等

```js
window.addEventListener('error', (error) => {
  console.log('捕获到异常：', error);
}, true)
```

**Promise异常**: 不能被 try-catch 和 window.onerror 捕获，如果没加 catch, 这时候我们就需要监听 unhandledrejection 来帮我们捕获这部分错误

```js
window.addEventListener("unhandledrejection", function (e) {
  e.preventDefault();
  console.log("捕获到 promise 错误了");
  console.log("错误的原因是", e.reason);
  console.log("Promise 对象是", e.promise);
  return true;
});

Promise.reject("promise error");
new Promise((resolve, reject) => {
  reject("promise error");
});
new Promise((resolve) => {
  resolve();
}).then(() => {
  throw "promise error";
});
```

**React 组件异常**: 错误边界是 React 组件，它“捕获子组件树中的任何地方的 JavaScript 错误”，同时还记录错误并显示回退用户界面

下面错误不能捕获：

- 事件处理器
- 异步代码
- 服务端的渲染代码
- 在 error boundaries 区域外的错误

```js
class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { hasError: false };
  }

  componentDidCatch(error, info) {
    // 展示出错的UI
    this.setState({ hasError: true });
    // 将错误信息上报到日志服务器
    logErrorToMyService(error, info);
  }

  render() {
    if (this.state.hasError) {
      // 可以展示自定义的错误样式
      return <h1>Something went wrong.</h1>;
    }
    return this.props.children;
  }
}

function App () {
  return (
    <ErrorBoundary>
      <MyWidget />
    </ErrorBoundary>
  )
}
```

**Vue 异常**：`Vue.config.errorHandler`

```js
Vue.config.errorHandler = (err, vm, info) => {
  console.error("通过vue errorHandler捕获的错误");
  console.error(err);
  console.error(vm);
  console.error(info);
};
```

**请求异常**: 请求拦截处理异常；成功访问后的代码执行，可以使用 try catch捕获

```js
// Add a response interceptor
axios.interceptors.response.use(
  function (response) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    // Do something with response error
  },
  function (error) {
    if (error.response.status === 401) {
      goLogin(); // 跳转登录页
    } else if (error.response.status === 502) {
      alert(error.response.data.message || "系统升级中，请稍后重试");
    }
    return Promise.reject(error.response);
  }
);

```

### 异常处理上报

> 上报异常：有很多成熟的方案可供选择： ARMS、fundebug、BadJS、Sentry

- 如果是服务器未知异常导致，可以阻塞用户操作，弹窗提示用户"服务器异常，请稍后重试"。并提供给用户一个刷新的按钮；
- 如果是数据异常导致，可阻塞用户操作，弹窗提示用户"服务器异常，请联系客服处理~"，同时将错误信息上报异常服务器，开发人员通过异常堆栈和用户埋点定位问题原因；
- 如果数据解析出错属于预料之中的情况，也有替代的默认值，那么当解析出错时直接使用默认值也可以；

## 总结

- 可疑区域增加 `try-catch`
- 全局监控 JS 异常 `window.onerror`
- 全局监控静态资源异常 `window.addEventListener`
- 捕获没有 catch 的 Promise 异常用 `unhandledrejection`
- `Vue errorHandler` 和 `React componentDidCatch`
- Axios 请求统一异常处理用拦截器 interceptors
- 使用日志监控服务收集用户错误信息
